amcl:
  ros__parameters:
    initial_pose_x: 1.0
    initial_pose_y: 1.0
    initial_pose_a: 0.0
    use_sim_time: true
    min_particles: 100
    max_particles: 5000
    transform_tolerance: 0.2

bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: base_footprint
    odom_topic: /odom
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_globally_updated_goal_condition_bt_node
      - nav2_is_path_valid_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 10.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"
    controller_plugins: ["FollowPath"]
    
    FollowPath:
      plugin: "nav2_dwb_controller::DWBLocalPlanner"
      min_vel_x: -0.22
      max_vel_x: 0.22
      min_vel_y: -0.0
      max_vel_y: 0.0
      min_vel_theta: -2.84
      max_vel_theta: 2.84
      acc_lim_x: 2.5
      acc_lim_y: 0.0
      acc_lim_theta: 3.2
      decel_lim_x: -2.5
      decel_lim_y: 0.0
      decel_lim_theta: -3.2

planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugins: ["GridBased"]
    expected_planner_frequency: 1.0
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: true
      allow_unknown: true

behavior_server:
  ros__parameters:
    use_sim_time: true
    behavior_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_spin_behavior/Spin"
    backup:
      plugin: "nav2_backup_behavior/BackUp"
    wait:
      plugin: "nav2_wait_behavior/Wait"

waypoint_follower:
  ros__parameters:
    use_sim_time: true

velocity_smoother:
  ros__parameters:
    use_sim_time: true
    speed_lim_v: 0.22
    speed_lim_w: 2.84
    accel_lim_v: 2.5
    accel_lim_w: 3.2
    decel_lim_v: -2.5
    decel_lim_w: -3.2

costmap_2d:
  ros__parameters:
    use_sim_time: true
    update_frequency: 5.0
    publish_frequency: 2.0
    global_frame: map
    robot_base_frame: base_footprint
    robot_radius: 0.22
    resolution: 0.05
    plugins: ["static_layer", "inflation_layer"]
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      map_subscribe_transient_local: true
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      cost_scaling_factor: 3.0
      inflation_radius: 0.55