slam_toolbox:
  ros__parameters:
    # Basic parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    
    # SLAM parameters
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_time_interval: 0.5
    transform_timeout: 0.0
    
    # Map resolution
    resolution: 0.05
    
    # Optimization parameters
    max_iterations: 50
    max_correspondence_distance: 1.0
    max_angular_correction_deg: 45.0
    max_linear_correction: 0.5
    
    # Loop closure
    loop_closure_search_distance: 5.0
    loop_closure_minimum_chain_size: 10
    loop_closure_min_response: 0.6
    
    # Map update
    throttle_scans: 1
    map_update_interval: 5.0
